language: node_js

node_js:
  - 12

env: 
  - 'DATABASE_URL=postgresql://postgres@localhost:5432/my_reg_test'

before_script:
  - npm install
  - psql -c 'create database  my_reg_test;' -U postgres
  - psql -U postgres -d my_reg_test -a -f reg-database_test.sql

services:
  - postgresql
addons:
  postgresql: '9.4'
  apt:
    packages:
      - postgresql-server-dev-9.4